name: x25519
description: Dart port of x25519 from Go Cryptography curve25519.
version: 0.1.1
homepage: https://github.com/Tougee/curve25519

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  adaptive_number: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.4
  hex: ^0.2.0
  benchmark_harness: ^2.0.0
